### ISSUE TITLE
[DynamoDB] Create sample data

### ISSUE THREAD

**Issue by wyapa** [gotechnica/mobile-backened#5]
Create sample data to test with

**Comment by ryan-ellis** [comment]
[sample_test.txt](https://github.com/gotechnica/mobile-backened/files/2281417/sample_test.txt)

This is what I started working on, let me know if I'm on the right track with this and if it's formatted how you want. Also for the general analytics, is that just going to have it's own table with one entry that we update or will it be shared somehow?

**Comment by ng-david** [comment]
@ryan-ellis
* I don't think we need the host name for each event, correct me if I'm wrong @wyapa  :)
* For favorited events, we are going to track each event by a unique ID number rather than name
* For each user, we also want a boolean for whether or not they're an organizer because we will be adding in organizers into the DB (organizers that log into the technica app will get a slightly different interface/features) 
* @wyapa Do we need their year in school or anything else on our sign up typeform for tracking analytics? 

Everything else looks okay to me!

**Comment by ng-david** [comment]
@robotal any thoughts on the sample dynamo data ryan has set up?

**Comment by wyapa** [comment]
- Host name might actually be a good call in case hackers want to connect after the event

- We're not storing ant schedule data in dynamo since that will be through GraphQL/Appsync and it falls under part 2

- For favorited events, it will also be through GraphQL/Appsync so it's not relevant for this

- School information isn't necessary but it might be better to keep it on if we need it in the future
